### ISSUE TITLE
Use run_list from .kitchen.yml with -K

### ISSUE THREAD

**Issue by arr-dev** [mlafeldt/chef-runner#55]
When using `-K` option, we should also load the run list defined for given instance.

I could give a go at implementing this if you agree?

**Comment by mlafeldt** [comment]
I'm not sure.

At the moment, the run list is determined in [main.go](https://github.com/mlafeldt/chef-runner/blob/81ec1a28035d32b181d41b3def3d532cdab73529/main.go#L105-L130). This logic is completely independent from the drivers, which only care about getting rsync and ssh to work.

While I see the use case, I'm afraid this would make things a lot more complicated. For example, what if both `-j` and `-K` were specified? Also, if we parse the Kitchen config for the run list, we should also parse the attributes. And on and on it goes.

What do you think?

**Comment by arr-dev** [comment]
Yeah, I've looked into code and it does seem it would take lot of refactoring to make it work
and it brings a lot of new edge cases.
I'll just have to pass the run list parsed with some ruby
