### ISSUE TITLE
Berksfile load error

### ISSUE THREAD

**Issue by mgdevstack** [mlafeldt/chef-runner#59]
My current working directory is m_java (cookbook) where Berksfile is present but runnning chef-runner is not able to load Berksfile and preventing further execution. Please assist me with necessary steps

![screenshot from 2016-01-20 00 27 00](https://cloud.githubusercontent.com/assets/8110509/12428827/f3d86534-bf0c-11e5-8142-7bb1d9b9acbb.png)

**Comment by mlafeldt** [comment]
There's no `Gemfile`. Do you have Berkshelf installed globally?

Please post your `Berksfile`, so I can reproduce the issue.

**Comment by aight8** [comment]
Similar error:
```
INFO: Starting chef-runner (v0.9.0 darwin/amd64)
INFO: Run list is [jobjungle::default]
INFO: Preparing local files
INFO: Installing cookbook dependencies with Berkshelf resolver
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- berkshelf (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
ERROR: exit status 1
```

OS: mac OS sierra beta 2

**Comment by mlafeldt** [comment]
Same question: do you have Berkshelf installed? Either globally or using Bundler?

**Comment by aight8** [comment]
Solution: install rbenv or custom ruby. Doesn't work with system ruby.
