### ISSUE TITLE
Version Pin

### ISSUE THREAD

**Issue by TheNotary** [mlafeldt/chef-runner#63]
Upon installing chef using `curl -L https://www.opscode.com/chef/install.sh | bash` I encounter the following WARNING:

```
WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

You are installing an omnibus package without a version pin.  If you are installing
on production servers via an automated process this is DANGEROUS and you will
be upgraded without warning on new releases, even to new major releases.
Letting the version float is only appropriate in desktop, test, development or
CI/CD environments.

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
```

How do you install an omnibus package with a version pin?

**Comment by mlafeldt** [comment]
You can specify a specific version via `-v`. See https://docs.chef.io/install_omnibus.html

chef-runner can also install Chef for you. See https://github.com/mlafeldt/chef-runner/wiki/Installing-Chef
